### ISSUE TITLE
Invalid config... required key not provided @ data [ 'username']

### ISSUE THREAD

**Issue by jimbob1001** [custom-components/sensor.trakt#1]
Hello, 

Top work on this  - just trying it out and have created a new id and secret but get an error that my config is missing a username...

EDIT: whoops, missed off some of the error message - it has two lines...

Invalid config for [sensor.trakt]: required key not provided @ data [ 'secret']. Got None.
Invalid config for [sensor.trakt]: required key not provided @ data [ 'username']. Got None.

my config was copied and pasted from here (i have tried adding the info to secrets as well as directly in the config )...

    - platform: trakt
      id: !secret trakt_id
      key: !secret trakt_key
      days: 10

also being very pedantic, but trakt calls them 'Client ID' & 'Client Secret' not 'ID' & 'Key'!

Cheers,
James

**Comment by ludeeus** [comment]
@jimbob1001 For this you need to configure these options:
```yaml
  - platform: trakt
    id: your_api_id
    secret: your_api_secret
    username: your_username
    days: 10
```
