### ISSUE TITLE
Config error "Integration trakt not found when trying to verify its sensor platform."

### ISSUE THREAD

**Issue by PierreScerri** [custom-components/sensor.trakt#22]
Hi,

I'm getting the error in the Subject title with Hassio 0.92.1.  The sensor was working before (Hassio 0.91).

Trakt sensor defined thus:

```
- platform: trakt
  id: '0c0c477cd1e90d14etc...'
  secret: 'fb28c99db5010eetc...'
  username: myusername
  days: 10
  name: Upcoming Episodes
```
Upcoming media card installed here:
![Screen Shot 2019-04-29 at 19 03 24](https://user-images.githubusercontent.com/34303331/56913287-8551d880-6ab1-11e9-8f1c-8bec3e9a1963.png)

Lovelace reference like so:
```
resources:
  - type: module
    url: /customcards/custom-cards/tracker-card.js?track=true
  - type: js
    url: /customcards/custom-cards/upcoming-media-card.js?track=true
```

How can I fix it?

Thank you.
