### ISSUE TITLE
Trakt upcoming calendar is empty

### ISSUE THREAD

**Issue by fedebruni84** [custom-components/sensor.trakt#40]
## Version of Home Assistant

Latest (Home Assistant Supervised)

## Version of the custom_component

Latest (2.0.0)

## Configuration

Sensor Attributes:

```yaml

data: 
{}

attribution: Data provided by trakt.tv
unit_of_measurement: shows
friendly_name: Trakt Upcoming Calendar
icon: mdi:calendar

```

## Describe the bug

After setup the integration through UI, sensor is created but it’s empty.
## Debug log

```text

2020-05-03 09:31:55 WARNING (MainThread) [custom_components.trakt] Trakt upcoming calendar is empty

```
