### ISSUE TITLE
Unable to setup integration

### ISSUE THREAD

**Issue by dinghino** [custom-components/sensor.trakt#49]
## Version of Home Assistant

hassio 0.114.4
Frontend version: 20200811.0
HACS 1.5.2

## Version of the custom_component

2.0.1

## Configuration

nothing setup for trakt due to config_flow

```yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

wake_on_lan:
mobile_app:

frontend:
  themes: !include_dir_merge_named ./themes

hacs: !include core/hacs.yaml
mqtt: !include core/mqtt.yaml
duckdns: !include core/duckdns.yaml
influxdb: !include core/influxdb.yaml
speedtestdotnet: !include core/speedtest.yaml
homeassistant: !include core/homeassistant.yaml

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

panel_iframe: !include_dir_named panels/

scene: !include scenes.yaml
script: !include scripts.yaml
automation: !include automations.yaml

group: !include_dir_merge_named groups/
light: !include_dir_merge_list lights/
switch: !include_dir_merge_list switches/
device_tracker: !include_dir_merge_list device_trackers/
sensor: !include_dir_merge_list sensors/

logger:
  default: info
  logs:
    custom_components.hacs: debug
    hacs: debug
```

## Describe the bug

I'm trying to install and setup the integration through HACS or manually, can't find it in the _add integration_ menu in the configurator.

Already tried to completely remove the files, restarted home assistant multiple times. The only log i get is the warning for the integration not being tested, so it seems like it knows it exists.

## Debug log

```text

2020-09-02 20:47:05 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for trakt which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
```
