### ISSUE TITLE
Connection pool is full, discarding connection: api.trakt.tv. Connection pool size: 10

### ISSUE THREAD

**Issue by bcutter** [custom-components/sensor.trakt#79]
## Version of Home Assistant
2024.7

## Version of the custom_component
3.0.1

## Configuration

```yaml

Logger: urllib3.connectionpool
Quelle: /usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py:323
Erstmals aufgetreten: 22:35:31 (15 Vorkommnisse)
Zuletzt protokolliert: 22:35:32

Connection pool is full, discarding connection: api.trakt.tv. Connection pool size: 10

```

## Describe the bug
Once upgraded from v2 to latest v3.0.1, this message appeared in the HA LOG

## Debug log

```text

Add your logs here.

```
